GET http://localhost:5000/games HTTP/1.1

###
GET http://localhost:5000/genres HTTP/1.1

###
GET http://localhost:5000/games/gam_019f0136-a376-72ee-8acc-c83ebb0d28fe

### 
POST http://localhost:5000/games
Content-Type: application/json
Accept: application/json

{
    "name": "Mortal Kombat 11",
    "description": "A fighting game developed by NetherRealm Studios",
    "genreId": "gen_019f0123-eeb1-7ec5-9dd7-208f84a5a27e",
    "price": 59.99,
    "releaseDate": "2017-03-03"
}


###
PUT http://localhost:5000/games/gam_019ee6b6-8ef1-778f-80d9-5f130d609860
Content-Type: application/json
Accept: application/json

{
    "name": "Mortal Kombat 11: Ultimate Edition",
    "genreId": "gen_019ee6b5-a483-7efd-a688-bb791f86f478",
    "description": "The ultimate edition of the fighting game developed by NetherRealm Studios",
    "price": 39.99,
    "releaseDate": "2020-02-14"
}

###
DELETE http://localhost:5000/games/gam_019ee6b6-8ef1-778f-80d9-5f130d609860
Content-Type: application/json