GET http://localhost:5000/games HTTP/1.1

###
GET http://localhost:5000/genres HTTP/1.1

###
GET http://localhost:5000/games/gam_019ed360-3fe4-79fd-b1b9-c67f39c5bbb3

### 
POST http://localhost:5000/games
Content-Type: application/json
Accept: application/json

{
    "name": "Mortal Kombat 11",
    "description": "A fighting game developed by NetherRealm Studios",
    "genre": "Fighting",
    "price": 59.99,
    "releaseDate": "2017-03-03"
}


###
PUT http://localhost:5000/games/gam_019ea4fb-e8f9-7193-a165-35ff42ae89cf
Content-Type: application/json
Accept: application/json

{
    "name": "Mortal Kombat 11: Ultimate Edition",
    "genre": "Fighting",
    "description": "The ultimate edition of the fighting game developed by NetherRealm Studios",
    "price": 39.99,
    "releaseDate": "2020-02-14"
}

###
DELETE http://localhost:5000/games/gam_019ea4fb-e8f9-7193-a165-35ff42ae89cf
Content-Type: application/json